mariux/fix
mineiros-io/terraform-google-organization-policy pull request #3
Opened 2022-03-31 18:21 UTC by mariux

- fix: spec usage
- feat: Add support for module_timeouts
- chore: prepare 0.0.2 release

2022-03-31 19:41 UTC, soerenmartius requested changes

2022-03-31 19:42 UTC, soerenmartius commented
Please add to the CHANGELOG.md also

2022-04-01 09:08 UTC, mariux commented
> Please add to the CHANGELOG.md also

why? the changelog is complete. its the initial release.

2022-04-01 09:41 UTC, soerenmartius approved these changes
lgtm

2022-04-01 11:13 UTC, merged